---
title: "Vehicle Arrival Study"
description: |

author:
  - name: ECIV 340L, CEE, UofSC
    url: {}
date: 11-05-2021
output:
  distill::distill_article:
    toc: true
    toc_float: true
    toc_depth: 3
editor_options: 
  markdown: 
    wrap: 72
---

```{=html}
<style>
body {
text-align: justify}
</style>
```
```{r, echo=FALSE}
library(fontawesome)
```

RELATED RESOUCES:

-   `r fa(name = "fas fa-check-circle", fill = "green")` [**LECTURE
    SLIDES**](https://emailsc-my.sharepoint.com/:p:/g/personal/ahmedf_email_sc_edu/EYhp2QOT3B1FvoG9p7eVq_4BkiwVVkLaTuOR4nm2BgpX8A?e=k5lTWY)
-   `r fa(name = "fas fa-check-circle", fill = "green")` [**DATA
    FORM**](https://emailsc-my.sharepoint.com/:b:/g/personal/ahmedf_email_sc_edu/EbwxL_SWF_9Krc6RAt5OWxkBHupXho7D9cvOAo3apkECxw?e=VUPOTc)
-   \``r fa(name = "fas fa-check-circle", fill = "green")` [**DEMO
    CALCULATION**](https://emailsc-my.sharepoint.com/:x:/g/personal/ahmedf_email_sc_edu/EbKZbvVATHlNioR1xuP09XUBOf9LDStB-cCOOK_KZTrLVQ?e=r8QVkb)

# INTRODUCTION

Many theoretical analyses of intersections assume that vehicles arrive
at an intersection in a random fashion. The ability to verify that
traffic arrives in a statistically random pattern is of great value to
the traffic engineer. For example, procedures from the Highway Capacity
Manual for the analysis of signalized intersections require the analyst
to state whether the traffic stream follows a random pattern or is
affected by some other source, such as a signal upstream from the
approach. The Poisson distribution is a simple, random, statistical
distribution. It is referred to as a counting distribution used to
predict the number of occurrences of an event within a certain interval.
Often, when used in traffic engineering, the occurrences are vehicle
arriving, and the time interval is cycle length. The Poisson equation
can be used to estimate the number of vehicles arriving at an
intersection within a given time span so that the amount of green needed
to process a predicted number of vehicles can be estimated. In
conjunction with the saturation flow rate, the Poisson distribution is
used to estimate the number of signal cycles that will successfully
process the approach traffic and the number that can be expected to
fail. Also, when left-turning traffic is of concern, the length of a
left-turn lane can be estimated by using this random distribution. This
lab session has two objectives. First, it provides a procedure for
estimating the randomness of the traffic stream by comparing field
measurements to computed theoretical values. Secondly, it demonstrates
how a statistical distribution can be used in conjunction with
field-measured saturation flow rates, startup delays, and volumes to
calculate the minimum green time for an approach to an intersection.

# EQUIPMENT

The equipment list for data collection procedure is a stopwatch (cell
phone) and note-taking materials.

# DATA COLLECTION

1.  **Select a signalized intersection that has sufficient traffic to
    accomplish the session**\
    The student group must first decide which lanes or lane groups
    should be measured. A lane group can be thought of as one lane or
    group of lanes from which drivers can complete the same move during
    the same phase. For instance, an exclusive left-turn and a combined
    right-turn and through-lane are examined as two separate lane
    groups. The Poisson distribution would be applied separately for
    each of the two lane groups. However, a combined left-turn and
    through-lane and a combined right-turn and through-lane approach
    controlled by a single-signal phase would be one lane group, and the
    lab session would look at the distribution for the entire lane
    group. Each of the lanes should have sufficient traffic for 0 to 6
    or more vehicles to arrive per twenty-second interval. This will
    provide a sufficient number of data points for the analysis.

2.  **For 100 consecutive twenty-second intervals, record the number of
    vehicles arriving at the intersection during each interva**l\
    The interval length will affect the quality of the results and
    should be chosen carefully. The twenty-second interval offers both
    enough observations and a reasonable time in the field. An interval
    shorter than 15 seconds would yield very few points for the
    probability curve and not allow a significant comparison to the
    theoretical Poisson distribution. On the other hand, longer interval
    lengths necessitate longer and impractical field-data collection
    periods. The data collection will be done for each of the lanes
    separately but can be accomplished concurrently. The student group
    can accomplish this task by designating a point on the approach to
    the intersection for determining whether a vehicle has arrived. This
    point is best chosen upstream of the intersection but before the
    point representing the maximum queue for that lane. This will allow
    vehicles arriving at the intersection to be counted without
    interference from the queue of vehicles waiting at the intersection
    when the signal is red. In many instances, the best location for
    this point will be the beginning of the separate left-turn lane. A
    data collection form is attached to this handout.

3.  **Check your work before leaving the field**\
    Before leaving the field, the data collection form should be checked
    to see that all field data have been collected correctly. Any
    unusual observations should be listed as comments.

# DATA ANALYSIS

1.  **Summarize field data on form provided**\
    A Poisson Distribution Data Summary Form is attached to this
    handout. Key to the understanding of the Poisson distribution is to
    take great care in the treatment of the collected materials; small
    errors can have a serious effect on results. For the 100
    observations recorded, sum those having the same number of vehicles
    observed, and enter it in the corresponding row. When complete, sum
    the values in Column 2 and check to see that the total equals the
    number of intervals observed. Next, calculate the number of vehicles
    observed. Multiply the values in Column 1 by the values in Column 2,
    and enter the product in Column 3. The sum of the values in Column 3
    is the total number of vehicles arriving during the observation
    period. Divide this total by the total number of intervals observed
    to yield the average number of vehicles arriving during the
    20-seconds interval. This is the average arrival rate (m or AAR) and
    will be used in the Poisson equation to calculate theoretical
    probabilities.

2.  **Calculate observed probabilities**\
    An assessment of traffic randomness requires a comparison of the
    observed distribution of arrivals to the theoretical distribution of
    arrivals. To do this, it is necessary to compute the observed
    probabilities. The observed probability is a measure of the
    likelihood that an observer randomly choosing a 20-second interval
    would witness a particular number of vehicles arriving. The values
    are a result of dividing the observed frequency for each level by
    the total number of observed intervals, or Column 2 divided by the
    sum of Column 2. The cumulative probability represents the
    likelihood a group will count a particular number of vehicles, or
    less, during a randomly selected interval. It is computed by adding
    all of the observed probabilities for that value and all lower
    values.

3.  **Compute theoretical Poisson probabilities**\
    Once the actual cumulative probability has been computed, the
    theoretical values are calculated using the Poisson equation. If the
    distribution of arrival is a random one, then the theoretical and
    observed values should be close. The form of the Poisson equation to
    be used is as follows:\
    \
    $Pr(X)= \frac{m^xe^{-m}}{x!}$\
    \
    where m is the average arrival rate, x is the number of vehicles
    expected to arrive and the constant e is the base for natural
    logarithms. For instance, the computed probability of exactly two
    vehicles arriving during an interval is $0.2225$, or $22.25%$, and
    is calculated using $m = 1.24$ vehicles per interval, and x = 2
    vehicles. The cumulative Poisson probabilities in the last column
    are calculated, similarly to the cumulative observed probabilities,
    by adding all values up to, and indicating, the row of interest. The
    probability that two or fewer vehicles will arrive is theoretically
    $0.2894$ plus $0.3588$ plus $0.2225$ or $0.8707$.

4.  **Compare observed probabilities to Poisson probabilities** The
    statistically valid method to compare field observations to a
    theoretical distribution is to apply a Chi-squared test, the
    application of which is demonstrated here. The question to be
    answered is whether the collected data indicate that the Poisson
    equation is a good indicator of how vehicles arrive at the
    intersection. Also, recognizing the limited number of data gathered,
    would it be unreasonable to use a Poisson distribution to forecast
    future events, such as the change in the capacity of an approach
    because of a change in green time or to find the length of a turning
    lane? Comparing cumulative-observed and cumulative-theoretical
    probabilities in the example data summary yield some interesting
    results. For this example, the values compare favorably, especially
    at the higher levels. The predicted values are within three percent
    of the observed values. So, it appears reasonable to use the Poisson
    equation to predict arrivals on this approach. However, the
    Goodness-of-Fit must be applied before proceeding. In a nutshell,
    the Goodness-of-Fit test identifies significant differences between
    the expected values and the observed values by computing the
    statistic Chi-squared, $\chi^2$, and comparing the computed value to
    the standard $\chi^2$ value. The following equation is used for the
    computation: $$\chi^2 = \sum_{i=1}^k \frac{(o_i-e_i)^2}{e_i}$$

where the symbols o_i and e_i represent the observed and expected
frequencies, respectively, for the i-th cell. The decision criteria
should not be used if the expected frequency of a cell is less than
five. The observed and expected frequencies computed using the Poisson
equation are shown below. The Goodness-of-Fit test will be applied to
this data to determine if the Poisson distribution properly reflects
driver behavior on this approach. If the Poisson distribution is a good
estimator of the arrivals, then the tabular or theoretical Chi-squared
will be greater than the computed Chi-squared. In order to identify the
proper Chi-squared, the number of degrees of freedom must be found. By
definition, the number of degrees of freedom in a Chi-square
goodness-of-fit test is equal to the number of cells minus 1. Computing
the $\chi^2$ using the stated equation yields the following:

Data Summary Number of Vehicles Observed Frequency Computed Frequency:

| \# veh | Observed Freq. | Computed Freq. |
|:------:|:--------------:|:--------------:|
|   0    |       34       |      28.9      |
|   1    |       34       |      35.9      |
|   2    |       16       |      22.2      |
|   3    |       9        |      9.2       |
|   4    |       5        |      2.9       |
|   5    |       1        |      0.7       |
|   6    |       1        |      0.2       |

The student will notice that the values for 3, 4, 5, and 6 vehicles were
combined because the number of observations (computed frequency) in the
cells was less than 5.

$\chi^2 =\frac{(34-28.9)^2}{28.9}+\frac{(34-35.9)^2}{35.9}+\frac{(16-22.2)^2}{22.2}+\frac{(16-13)^2}{13}$

$\chi^2=3.424$

For this example, the average arrival rate was the only quantity
obtained from the observed data used to compute the Poisson frequencies.
Therefore, the number of degrees of freedom for this example is
$4 - 1 = 3$. From the table, $\chi^2_{0.05}=7.81$ and
$3.424\ \le\ 7.81$, so it can be concluded that the Poisson distribution
provides a good fit for the distribution of arrival rates.

5.  **Calculate maximum arrivals** The next step in the analysis focuses
    on the application of the Poisson equation to the identification of
    the capacity of a lane group. The values presented will be
    hypothetical, but the reader may wish to refer to the saturation
    flow rate. Should a quick determination of an existing approach be
    desired, then the length of the cycle and the length of green time
    would be useful. Note that many signal timing procedures exist, and
    the application of a Poisson distribution is but one of them.
    Determining the capacity of an existing lane group, or the minimum
    green time required, can be accomplished using the Poisson equation.
    It is used to determine the highest number of vehicles that may be
    expected to arrive during a signal cycle. Knowing this number, the
    saturation flow rate and startup delay can be used to compute the
    minimum green time needed to process the traffic. First, however,
    the analyst must determine how often the signal should be able to
    process all of the demand. Since it is usually impossible to time a
    signal to process all levels of traffic all the time, a level of
    acceptance is chosen. For this example, the signal should exhibit
    sufficient green time to process the traffic for 9 out 10 cycles.
    The Poisson equation can be used to calculate the maximum number of
    vehicles expected to arrive during 90% of the cycles. So, timing the
    green-signal time to process this traffic would result in the green
    time being insufficient only 10% of the time. Calculating the
    maximum number of vehicles expected to arrive in 9 of 10 cycles is
    computed using the cumulative Poisson distribution. If the cycle
    length is 60 seconds and the demand volume is 180 vehicles per hour,
    then the average arrival rate is (180)(60)/3600 = 3 vehicles per
    cycle. Now, let us consider the class example. Calculating the
    probabilities of exactly 0, 1, 2, ... vehicles arriving during the
    cycle and summing the values, 3 is the maximum number of vehicles
    expected. The computed probability of having 3, or less, vehicles
    arriving during the cycle is 0.963 or 96.3%. Therefore, allocating
    sufficient green time to process three vehicles should allow the
    approach to process all of the traffic 96.3% of the time.

6.  **Calculate minimum green time** The minimum green time can be
    calculated using the saturation flow rate and startup delay for the
    approach. For this example, it may be assumed that the saturation
    flow rate is 1800 vehicles per hour of green time and the startup
    delay is 3 seconds. Using these values, the minimum green time is
    calculated by the equation 3 + (3600/1800) X = G, where X equals the
    number of vehicles which must be processed and G is the minimum
    green time needed to move the traffic. Substituting X = 3 vehicles,
    the equation yields a green time of 9 seconds.

7.  **Summarize and draw conclusions** The student group should
    summarize the findings and draw conclusions from the effort.
    Questions to be addressed are:

    1.  Does the Poisson equation provide a good indication of driver
        behavior at this intersection?

    2.  Can it be used to predict the minimum green time needed?

    3.  Should observed frequencies be used for analysis at this
        location rather than the Poisson theoretical frequencies?

    4.  Does this effort indicate that statistical functions are useful
        in traffic engineering?
