---
title: "Headway Study"
description: |

author:
  - name: ECIV 340L, CEE, UofSC
    url: {}
date: 10-22-2021
output:
  distill::distill_article:
    toc: true
    toc_float: true
    toc_depth: 3
editor_options: 
  markdown: 
    wrap: 72
---

```{=html}
<style>
body {
text-align: justify}
</style>
```
```{r, echo=FALSE}
library(fontawesome)
```

RELATED RESOUCES:

-   `r fa(name = "fas fa-check-circle", fill = "green")` [**LECTURE
    SLIDES**](https://emailsc-my.sharepoint.com/:p:/g/personal/ahmedf_email_sc_edu/EXtCFYQJ4GRLn9_p5n4k3ZQBAx9EthgT5kYJkFwPh292iA?e=imDJ8O)
-   `r fa(name = "fas fa-check-circle", fill = "green")` [**DATA
    FORM**](https://emailsc-my.sharepoint.com/:b:/g/personal/ahmedf_email_sc_edu/EYi5ZStYdmpEpMWqIRxID-8BnerVjANjysGS2jnfwCsGPg?e=UJR3qM)
-   \``r fa(name = "fas fa-check-circle", fill = "green")` [**DEMO
    CALCULATION**](https://emailsc-my.sharepoint.com/:x:/g/personal/ahmedf_email_sc_edu/EZfzwW7fHHZLr88lyNo9LMMBFulv7yWZVSmzUM6Yy5FVYg?e=rRhrW2)
-   \``r fa(name = "fas fa-check-circle", fill = "green")` [**DEMO
    CALCULATION-2**](https://emailsc-my.sharepoint.com/:x:/g/personal/ahmedf_email_sc_edu/Ecx_4x50QRlFreQfdcB5Z18BeYpvmti1e7Hzns9Q98NUoQ?e=9N0Dyi)

# INTRODUCTION

In the analysis of unsignalized intersections, it is important to know
the minimum size of the headway in traffic flow that drivers are willing
to accept when entering or crossing a traffic stream. The length of a
headway is measured from the front of one vehicle to the bumper of the
next. Although many methods exist to compute the expected number of
headways of a given size in the traffic stream, the traffic engineer
usually must assume the minimum headway drivers actually will use. Based
on this assumption, there are methods to identify the level of service
at an intersection, as well as the capacity of each of its approaches.
For instance, the 2010 Highway Capacity Manual's analysis methodology
assumes a minimum acceptable headway in the flow of conflicting traffic
through an intersection without signals, then computes the level of
service and capacity for each of the movements. Pedestrians preparing to
cross the roadway must assess the headways in the conflicting traffic,
determine when one of sufficient length exists, and decide if they will
cross. Again, there is a methodology that allows the investigator to
compute the number and size of the headway expected and identifies
whether there are sufficient headways to allow safe pedestrian passage.
However, all of the computation methods require identification of the
minimum headway before calculations can be made.

Equipment The equipment list for data collection procedure is a
stopwatch (cell phone) and note-taking materials.

# Data Collection

1.  Visit the site, and choose a location and time to collect the data
    For this lab session, the student groups will gather data to
    identify the minimum acceptable headway for left-turn and right-turn
    traffic from the minor roadway using simulation video. The major
    roadway should have relatively high volume.

2.  Collect and record the data A time headway is measured from the time
    the last conflicting vehicle passes the intersection until the next
    conflicting vehicle passes it. A useable headway is one that a
    minor-road vehicle uses to execute a maneuver. Use the attached form
    to record the useable headways (in seconds) in the conflicting
    traffic. For the right-turn maneuver, the conflicting traffic
    consists of only the vehicles traveling in the near lanes of the
    major highway---those lanes in which the right-turning vehicle will
    merge. For instance, if the minor traffic approaches the
    intersection northbound and wishes to travel eastbound (turn right)
    on the major roadway, then only the eastbound traffic conflicts with
    the movement. Likewise, should the vehicle wish to travel westbound
    (turn left) on the major road, then both eastbound and westbound
    traffic are conflicting. For each minor-approach vehicle, the
    headway that is used is measured and the time is recorded. Should a
    vehicle arrive at the intersection and not have to wait for a
    conflicting vehicle to pass before proceeding, then the time is
    measured from when the vehicle moves into the intersection until the
    next conflicting vehicle arrives. Should multiple vehicles use the
    headway, only the first vehicle is recorded as passing and the size
    of the headway is measured. ***At least 50 left turns and 50 right
    turns from the minor roadway should be observed.***

3.  Check your work before leaving the field Before leaving the field,
    the data collection form should be checked to see that all field
    data have been collected correctly. Any unusual observations should
    be listed as comments.

# Data Analysis

1.  Summarize field data on the provided form To properly arrive at a
    minimum useable headway, the collected observations need to be
    summarized. The Headway Study Data Summary Form attached to this
    handout allows for the headways to be grouped in 0.25-seconds
    increments. For the first increment (3.0 entry in the "headway"
    column), the number of headways measuring 3.0 to 3.25, inclusive, is
    entered in the "# Observed" column. The frequency is computed by
    dividing the entry by the total number of observations. The
    cumulative frequency is computed by summing all frequencies up to,
    and including, the row being calculated. The calculation is similar
    to that performed in Session 1 (Spot Speed Study).

2.  Identify minimum acceptable headway Identification of the minimum
    acceptable headway from the observations requires a criterion. In
    traffic engineering, a criterion is usually expressed in percent of
    drivers or vehicles for which a design standard applies. This
    recognizes that traffic engineers cannot design for every
    vehicle-driver combination. For this lab session, an 85% acceptance
    rate will be the criterion. Therefore, the student wishes to
    identify the smallest headway that 85% or more of the drivers
    observed would use. This value is identified by scanning down the
    "Cumulative Frequency" column until the first entry is found that is
    ≥0.15. The maximum headway size for that row is the minimum headway
    that 85% of the observed drivers need in order to execute that
    maneuver. For instance, if the 5.25-second row has a cumulative
    frequency of 0.16 for the left-turn move, then the minimum
    acceptable headways can be said to be 5.50 seconds---the upper limit
    of the group. That means 84% of the drivers will use a headway at
    least 5.50 seconds in length.

3.  Compare observed values to standardized values The student should
    compare the observed minimum headways to the standard values used in
    Highway Capacity Manual (HCM) analyses. The HCM uses the minimum
    headways shown in the following

|        Veh. Maneuver         | 2-lane Major Road | 2-lane Major Road |
|:----------------------------:|:-----------------:|:-----------------:|
| Right turn from minor street |       6.2 s       |       6.9 s       |
| Left turn from minor street  |       7.1 s       |       7.5 s       |

: Base Critical Headway (HCM, 2010)

4.  Estimate the Probability of the minimum acceptable headway occurring
    in the traffic stream and the number of acceptable headways expected
    Once an acceptable headway has been identified, both the number and
    frequency of headways occurring in the traffic stream can be
    calculated. Based on the assumption that vehicle arrivals on the
    main roadway are random arrivals and follow a Poisson distribution,
    then the probability of a headway, h, in seconds being greater than,
    or equal to, a specified value, t, in seconds is:

$Pr⁡(h≥t)=e^(-qt/3600)$

where q= flow in vehicles per hour. Given a minimum acceptable headway
of 5.50 seconds, the probability of headways greater than, or equal to,
this minimum value on a roadway with 300 vehicles per hour is 0.632 or
63.2%. Additionally, the expected number of acceptable headways that may
be expected can be calculated by multiplying the vehicle volume, minus
one, by the probability. For the calculation completed:

$Frequency=(q-1)× e^{-qt/3600} =(300-1)×0.632 = 189 "headways\ per\ hour$

This indicates that sufficient headways in the traffic exist at this
intersection for 189 vehicles per hour to be accommodated by the minor
approach.

5.  Summarize and draw conclusions The following questions can help the
    student summarize and interpret the results of the data and
    computations. Did the headways in the traffic stream appear to be
    random? If not, why not? Were there sufficient headways to allow the
    proper flow of traffic from the minor roadway? Was the minimum
    acceptable headway larger, smaller, or as expected? Is a 90%
    criterion reasonable or should different values be used at different
    locations? Do the HCM values properly represent driver behavior in
    the region? What other conclusions can be made from this study?

Input data for the report: Assume the flow of traffic,
$q = 450\ vehicles\ per\ hour.$
