---
title: "Transportation Modeling with TransCAD"
description: |

author:
  - name: ECIV 340L, CEE, UofSC
    url: {}
date: 11-19-2021
output:
  distill::distill_article:
    toc: true
    toc_float: true
    toc_depth: 4
editor_options: 
  markdown: 
    wrap: 72
---

```{=html}
<style>
body {
text-align: justify}
</style>
```


```{r, echo=FALSE}
library(fontawesome)
```

RELATED RESOUCES:

-   `r fa(name = "fas fa-check-circle", fill = "green")` [**LECTURE
    SLIDES**](https://emailsc-my.sharepoint.com/:p:/g/personal/ahmedf_email_sc_edu/EYhp2QOT3B1FvoG9p7eVq_4BkiwVVkLaTuOR4nm2BgpX8A?e=k5lTWY)
-   `r fa(name = "fas fa-check-circle", fill = "green")` [**DATA
    FORM**](https://emailsc-my.sharepoint.com/:b:/g/personal/ahmedf_email_sc_edu/EbwxL_SWF_9Krc6RAt5OWxkBHupXho7D9cvOAo3apkECxw?e=VUPOTc)
-   \``r fa(name = "fas fa-check-circle", fill = "green")` [**DEMO
    CALCULATION**](https://emailsc-my.sharepoint.com/:x:/g/personal/ahmedf_email_sc_edu/EbKZbvVATHlNioR1xuP09XUBOf9LDStB-cCOOK_KZTrLVQ?e=r8QVkb)

# INTRODUCTION

The purpose of this lab session is to perform travel demand modeling and
logistics analysis using TransCAD. First, you need to download the demo
files (TransCAD_demo.zip) from Blackboard. Then, open the TransCAD 8.0
(Academic 64-bit).

# Part I: Travel Demand Modeling

## Trip Generation (Production)

The goal of trip generation is to predict the number of trips that are
generated by and attracted to each zone in a study area. This is only
concerned with the number of trips that start and end in each zone, and
not with making connections between origins and destinations of trips.

There are three primary tools that are used in modeling trip production:

**Cross-Classification:**

Cross-classification methods separate the population in an urban area
into relatively homogeneous groups based on certain socio-economic
characteristics. Then, average trip production rates per household or
individual are empirically estimated for each classification. This
creates a lookup table that may be used to forecast trip productions.

**Regression Models:**

Two types of regressions are commonly used. The first uses data
aggregated at the zonal level, with average number of trips per
household in the zone as the dependent variable and average zonal
characteristics as the explanatory variables. The second uses
disaggregated data at the household or individual level, with the number
of trips made by a household or individual as the dependent variable and
the household and personal characteristics as the explanatory variables.

**Discrete Choice Models:**

Discrete choice models use disaggregate household or individual level
data to estimate the probability with which any household or individual
will make trips. The outcome can then be aggregated to predict the
number of trips produced.

### Task 1: Generating Productions by Cross-Classification

-   Step 1. Choose File > Open Workspace and open the workspace
    CrossClassification.wrk. TransCAD displays a map of Vermont zones
    and a cross-classification table.

-   Step 2. Choose Planning > Trip Productions > Cross-Classification to
    display the Cross-Classification box.

-   Step 3. Choose MCD from the Input Data drop-down list.

-   Step 4. Choose All Zones from the Using drop-down list and Vmt_crcl
    from the Trip Rate Table list.

-   Step 5. Choose all three trip purposes that are shown in the Rate
    Fields scroll list.

-   Step 6. Click Choose Segments to display the Choose Zone/Subzone
    fields dialog box.

-   Step 7. Click Households in the Available Fields scroll list and
    click Add>\>.

-   Step 8. Click OK to return to the Cross-Classification dialog box.

-   Step 9. Choose \[AUTO/HH\] from the drop-down list in the Avg Car/HH
    column and \[INC/HH\] from the drop-down list in the Avg Inc/HH
    column.

-   Step 10. Click OK to display the Output File Settings dialog box.

-   Step 11. Type "First Name-TG-CC" as the Output Table file name in
    the Short File Name column and click OK. TransCAD computes the
    productions for all zones and all purposes and displays a dataview
    of the cross-classification results in a joined view.

-   Step 12. Click Close to close the dialog box and scroll to the far
    right of the dataview to see the trip productions.

-   Step 13. Choose File > Close All to close the map and dataviews.

### Task 2: Estimating and Applying a Zonal Regression Model

-   Step 1. Choose File > Open and open the binary file TG_ZNREG.BIN.
    This database contains the census data on each tract in Nassau
    County, New York.

-   Step 2. Choose Statistics > Model Estimation to display the Model
    Estimation dialog box.

-   Step 3. Click the Regression radio button.

-   Step 4. Choose \[Work Trips Per HH\] from the Dependent Var
    drop-down list.

-   Step 5. Click Independent Variables to display the Choose
    Independent Variables dialog box.

-   Step 6. Control click on \[People Per HH\], \[Age\<=5 Per HH\],
    \[25+ College Grad %\], and \[Veh Per HH\] in the Available Fields
    scroll list and click add.

-   Step 7. Click OK to return to the Model Estimation dialog box.

-   Step 8. Click Estimate to estimate the model.

-   Step 9. Click Save Model to display the Save Model As dialog box.

-   Step 10. Type "First Name-TG-R" as the file name and click Save.

-   Step 11. TransCAD produces a .mod file (called First Name-TG-R.mod)
    that contains the estimated parameters of the regression equation,
    including goodness-of-fit measures, estimates of the coefficients,
    and t-statistics.

-   Step 12. Click Close to close the Model Estimation dialog box.

-   Step 13. Choose Planning > Trip Productions > Apply a Model.

-   Step 14. Choose the model file First Name-TG-R.mod and click Open to
    display the Forecast dialog box.

-   Step 15. Choose TG_ZNREG from the Apply To drop-down list.

-   Step 16. Choose \[Forecasted WTrips\] from the Results in drop-down
    list.

-   Step 17. Click the Regression radio button.

-   Step 18. Click OK. TransCAD applies the model to each record, stores
    the forecasted variable in the field \[Forecasted WTrips\] of the
    table TG_ZNREG, and displays the Results Summary dialog box.

-   Step 19. Click Close.

-   Step 20. Scroll to the far right to see the results. Step 21. Choose
    File > Close to close the dataview.

### Task 3: Estimating a Logit Model of Work Trip Production

-   Step 1. Choose File > Open and open the binary file Survey.bin. This
    database contains a subset of the fields from the PUMS person
    records for Delaware.

-   Step 2. Choose Statistics > Model Estimation to display the Model
    Estimation dialog box.

-   Step 3. Click the Binary Logit radio button.

-   Step 4. Choose \[Worked Last Week?\] from the Dependent Var
    drop-down list.

-   Step 5. Click Independent Variables to display the Independent
    Variables dialog box.

-   Step 6. Control click on \[Age over 16 ?\] , \[Age over 65 ?\] ,
    \[Male ?\] , and \[Non-White\] in the Available Fields scroll list,
    and click Add.

-   Step 7. Click OK.

-   Step 8. Click Estimate to estimate the model.

-   Step 9. Click Save Model to display the Save Model As dialog box.

-   Step 10. Type "First Name-TG-LM" as the File Name and click Save.

-   Step 11. TransCAD produces a .mod file (called First Name-TG-LM.mod)
    that contains the estimated parameters of the regression equation,
    writes the results to the master report file, including
    goodness-of-fit measures, estimates of the coefficients, and
    t-statistics.

-   Step 10. Click Close to close the Model Estimation dialog box.

-   Step 12. Choose File > Close to close the dataview.

## Trip Generation (Attraction)

In many ways, estimating trip attractions is similar to estimating trip
productions because the problem is the same: predicting the number of
trips attracted by relating the number or frequency of trips to the
characteristics of the individuals, the zone, and the transportation
network. Thus, the three methods described above may also be used to
estimate the number of trips attracted to a zone.

## Trip Distribution

Trip distribution models are used to predict the destination choices of
trip makers. Usually, in trip distribution a new flow matrix is
forecasted based on estimates of future productions and attractions and
estimates of the costs of travel between origins and destinations.

Trip distribution models can be applied at either an aggregate or a
disaggregate level. Aggregate trip distribution models are typically
used to predict flows between origin and destination zones. Three
categories of aggregate trip distribution methods predominate in urban
transportation planning:

**Growth Factor Methods:**

These involve scaling an existing matrix by applying multiplicative
factors to matrix cells. These methods are usually encountered when
there is no information available concerning the network interzonal
distances, travel times, or generalized costs.

**Gravity Models:**

The typical inputs include one or more flow matrices, an impedance
matrix reflecting the distance, time, or cost of travel between zones,
and estimates of future levels productions and attractions. The gravity
model explicitly relates flows between zones to interzonal impedance to
travel.

**Destination Choice Models:**

These generally take the form of discrete choice models that evaluate
utility functions for various potential destinations and ascribe
probabilities to the same. The utilities can be a function of
destination zone attributes as well as origin-destination skims.

### Task 4. Applying a Growth Factor Model

-   Step 1. Choose File > Open Workspace and open the workspace
    DistributionApplyGrowthFactor.WRK. A map of Utown and an O-D matrix
    are displayed.

-   Step 2. Choose Planning > Trip Distribution > Growth Factor Method
    to display the Growth Factor Balancing dialog box.

-   Step 3. Choose UTOWN Base OD from the Matrix File drop-down list.

-   Step 4. Choose Production from the Constraint Type radio list.

-   Step 5. Check the box next to the HBW matrix.

-   Step 6. Click on the cell in the Production column and choose
    \[HBW_P 2000\] from the drop-down list.

-   Step 7. Click OK to display the Output File Settings dialog box.

-   Step 8. Type "First Name-TD-GF" as the file name in the Short File
    Name cell and click OK. TransCAD applies the growth factor model and
    displays the Results dialog box.

-   Step 9. Click Close. TransCAD displays the Results Summary dialog
    box.

-   Step 10. Click Close. TransCAD displays the Growth Factor Balanced
    (HBW) matrix.

-   Step 11. Choose File > Close All to close all of the windows.

### Task 5: Applying a Gravity Model

-   Step 1. Choose File > Open Workspace and open the workspace
    DistributionApplyGravity.WRK. A map and a friction factor matrix are
    displayed.

-   Step 2. Choose Planning > Trip Distribution > Gravity Application to
    display the Gravity Application box.

-   Step 3. Choose TAZ from the Table drop-down list, FRICTION FACTORS
    from the FF Table drop-down list, TIME from the FF Time drop-down
    list, Doubly from the Constraint drop-down list, Shortest Path from
    the Impedance Matrix drop-down list, and None from the FF Matrix and
    K Matrix drop-down lists.

-   Step 4. Change the name of the Purpose 1 purpose by typing "HBW" in
    the cell in the Purpose row. HBW_P is automatically chosen in the
    Production row and HBW_A is automatically chosen in the Attraction
    row.

-   Step 5. Make the following changes to the HBW purpose: - Click on
    the cell in the Method row and choose Gamma from the drop-down
    list. - Type "20" in the Iteration row. This limits the procedure to
    a maximum of 20 iterations for this trip purpose. - Type 28507 for
    the value of a, 0.02 for the value of b, and 0.123 for the value
    of c. - Verify that Shortest Path - FF_Time is the chosen field in
    the Impedance Core row.

-   Step 6. Click "plus sign" to add a second purpose.

-   Step 7. Change the name of the new purpose to "HBNW." HBNW_P is
    automatically chosen in the Production row and HBNW_A is
    automatically chosen in the Attraction row.

-   Step 8. Make the following changes to the HBNW purpose: - Click on
    the cell in the Method row and choose Inverse from the drop-down
    list. - Type 1.4 for the value of b. - Verify that Shortest Path -
    FF_Time is the chosen field in the Impedance Core row.

-   Step 9. Click "plus sign" to add a third purpose.

-   Step 10. Change the name of the new purpose to "NHB." NHB_P is
    automatically chosen in the Production row and NHB_A is
    automatically chosen in the Attraction row.

-   Step 11. Make the following changes to the NHB purpose: - Click on
    the cell in the Method row and choose Table from the drop-down
    list. - Click on the cell in the F Factor row and choose NHB_FF from
    the drop-down list. - Verify that Shortest Path - FF_Time is the
    chosen field in the Impedance Core row.

-   Step 12. Click OK to display the Output File Settings dialog box.

-   Step 13. Type "First Name-TD-GM" as the file name in the Short File
    Name cell and click OK. TransCAD evaluates the three models,
    displays a Results dialog box stating that all three models
    converged.

-   Step 14. Click Close. TransCAD displays the Results Summary dialog
    box.

-   Step 15. Click Close. TransCAD displays a matrix view containing the
    results.

-   Step 16. Choose File > Close All to close all of the windows.

## Mode Choice

Mode choice models are used to analyze and predict the choices that
individuals or groups of individuals make in selecting the
transportation modes that are used for particular types of trips.
Typically, the goal is to predict the aggregate share or absolute number
of trips made by mode for each origin-destination pair. Mode choice
models may also be applied on disaggregate lists of individuals and are
often employed in Activity-Based Models. The modeling concepts
underlying mode choice models may also be applied to predict other
choices and shares such as household auto ownership splits, time of day
choice, etc. The mode choice component of a travel demand model is
estimated using individual-level data obtained from a survey, and
forecasts are subsequently based upon aggregate, zonal segment level
explanatory variables.

### Discrete Choice Models

Discrete choice models are in many respects a substitute for regression
models when the dependent variable is qualitative or categorical rather
than continuous. Discrete choice models are formulated as stochastic
models, in which the probability that a particular response is observed
is a function of a set of explanatory variables. There are a variety of
functional forms that can be proposed for the explanation of discrete
choice. The Multinomial Logit (MNL) and Nested Logit (NL) models are
used extensively.

**Multinomial Logit (MNL) Model**

MNL involves a decision-maker choosing exactly one alternative from a
set of available discrete alternatives. For example, the figure below
illustrated a mode choice situation in which individuals choose one of
Drive Alone, Carpool or Bus to make certain type(s) of trips:

### Task 6: Estimating an MNL Model

-   Step 1. Choose File > Open Workspace and open the workspace
    ModeChoiceEstimation.wrk.

-   Step 2. Choose Planning > Mode Split > Logit Model Estimation to
    open the Logit Model Estimation box.

-   Step 3. Click the Load button and select the model file
    MultinomialLogitModelEstimation.mdl.

-   Step 4. Click the Estimate tab and enter an output file name.

-   Step 5. Click Save and select a file name to save the model.

-   Step 6. Click Run. TransCAD estimates the MNL model, reports the
    results in a report form, and displays the Results Summary dialog
    box.

-   Step 7. Click Close. TransCAD opens the Load Confirmation dialog
    box. Click Yes.

-   Step 8. Click the Utilities tab. The Coefficient column now contains
    the new estimated parameters.

-   Step 9. Double-click on the nodes in the tree view window to see the
    estimated ASC values. Step 10. Choose File > Close All to close all
    the windows.

### Task 7: Applying an MNL Model on a Matrix

-   Step 1. Choose File > Open Workspace and open the workspace
    ModeChoiceAggregateApplication.wrk.

-   Step 2. Choose Planning > Mode Split > Logit Model Application to
    open the Logit Model Application box.

-   Step 3. Click the Load button and select the model file
    MultinomialLogitAggregateModel.mdl.

-   Step 4. Click the Apply tab and select additional outputs by
    checking "Output Utility Values" box.

-   Step 5. Check the "Open Outputs" box to ensure that the output files
    are opened after the model has been applied.

-   Step 6. Click Run.

-   Step 7. Click Yes in the Confirmation dialog box to save the
    changes, type "First Name-MC-MNL" as the file name and click Save.
    The Mode Choice Model Application Outputs dialog box is displayed
    with file names for each of the desired outputs.

-   Step 8. Check the Overwrite All Files box and click OK. TransCAD
    applies the Multinomial Logit model, reports the results in a report
    form, and displays the Results summary dialog box.

-   Step 9. Click Close. TransCAD opens the Utility, Probability and
    Applied Totals matrices. Step 10. Choose File > Close All to close
    all of the windows.

**Nested Logit (NL) Model**

When dealing with choice models that include several alternatives, there
often exist natural groupings of alternatives and/or a natural hierarchy
to the decision being made. A nested logit model is often represented
using a tree structure, which visually represents groupings or
hierarchies of the choice alternatives. For example, in mode choice, the
tree may be:

In this case, the decision process can be thought of as occurring at the
two levels. First, the traveler decides whether to take transit or auto.
If transit is chosen, the traveler further decides whether to take the
bus or light rail. Similarly, if auto is chosen, the traveler decides
whether to drive alone or carpool. However, note that it is in fact a
join decision, in that whether a traveler chooses transit or auto depend
on the characteristics of the lower level alternatives. The nested logit
model provides a mathematical representation of this joint decision.

### Task 8: Estimating a NL Model

-   Step 1. Choose File > Open Workspace and open the workspace
    ModeChoiceEstimation.wrk.

-   Step 2. Choose Planning > Mode Split > Logit Model Estimation to
    open the Logit Model Estimation box.

-   Step 3. Click the Load button and select the model file
    NestedLogitModelEstimation.mdl.

-   Step 4. Click the Estimate tab and enter an output file name.

-   Step 5. Click Save and select a file name to save the model.

-   Step 6. Click Run. TransCAD estimates the Nested Logit Model,
    reports the results in a report form and displays and the Results
    Summary dialog box.

-   Step 7. Click Close. TransCAD opens the Load Confirmation window.
    Click Yes.

-   Step 8. Click the Utilities tab. The Coefficient column row contains
    the new estimated parameters.

-   Step 9. Double-click on the nodes in the tree view window to see
    estimated values of the ASCs and Thetas.

-   Step 10. Choose File > Close All to close all of the windows.

### Task 9: Applying a NL Model on a Matrix

-   Step 1. Choose File > Open Workspace and open the workspace
    ModeChoiceAggregateApplication.wrk.

-   Step 2. Choose Planning > Mode Split > Logit Model Application to
    open the Logit Model Application box.

-   Step 3. Click the Load button and select the model file
    NestedLogitAggregateModel.mdl.

-   Step 4. Click the Apply tab and select additional outputs by
    checking the "Output Logsum Values" and "Output Utility Values"
    boxes.

-   Step 5. Check the "Open Outputs" box to ensure that the output files
    are opened after the model has been applied.

-   Step 6. Click Run.

-   Step 7. Click Yes in the Confirmation dialog box to save the
    changes, type "First Name-MC-NL" as the file name and click Save.
    The Mode Choice Model Application Outputs dialog box is displayed
    with file names for each of the desired outputs.

-   Step 8. Check the "Overwrite all files" box and click OK. TransCAD
    applies the Nested Logit model, reports the results in a report form
    and displays the Results Summary dialog box.

-   Step 9. Click Close. TransCAD opens the Utility, Logsum, Probability
    and Applied Totals matrices.

-   Step 10. Choose File > Close All to close all of the windows.

## Traffic Assignment

Traffic assignment models are used to estimate the traffic flows on a
network. These models take as input a matrix of flows that indicate the
volume of traffic between origin and destination (O-D) pairs. They also
take input on the network topology, link characteristics, and link
performance functions. The flows for each O-D pair are loaded onto the
network based on the travel time or impedance of the alternative paths
that could carry this traffic. TransCAD provides the widest array of
traffic assignment procedures that can be used for modeling urban
traffic. These procedures include numerous variants that can be used for
modeling intercity passenger and freight traffic.

Traffic assignment is a key element in the urban travel demand
forecasting process. The traffic assignment model predicts the network
flows that are associated with future planning scenarios and generates
estimates of the link travel times and related attributes that are the
basis for benefits estimation and air quality impacts. The traffic
assignment model is also used to generate the estimates of network
performance that are used in the mode choice and trip distribution or
destination choice stages of many models.

### User Equilibrium (UE)

Assignment UE assignment is the recommended method for traffic
assignment unless a more advanced model is employed. UE procedures use
an iterative process to achieve a convergent solution, in which no
travelers can improve their travel times by shifting routes. In each
iteration, TransCAD computes network link flows that are based upon
flow-dependent travel times. The formulation of the UE problem is a
mathematical program and the Frank-Wolfe (FW) solution method is one of
several employed in TransCAD. Another way to compute a UE assignment is
to use an alternative algorithm such as path-based algorithm.

### System Optimum (SO)

Assignment SO computes an assignment that minimizes total travel time on
the network. Under SO assignment, no users can change routes without
increasing the total travel time on the system, although it is possible
that travelers could reduce their own travel times. SO assignment can be
thought of as a model in which total system cost is minimized when
travelers are told which routes to use. Obviously not a behaviorally
realistic model, SO assignment can be useful in analyzing Intelligent
Transportation System (ITS) scenarios.

### Task 10: Performing a User Equilibrium Traffic Assignment

-   Step 1. Choose File > Open Workspace, then open the workspace
    TrafficAssign.wrk. TransCAD displays a street map and a flow matrix.
    You want to assign flow to the links using the User Equilibrium
    model.

-   Step 2. Choose Planning > Static Traffic Assignment > Traffic
    Assignment to display the Traffic Assignment dialog box.

-   Step 3. Choose N-Conjugate UE from the Method drop-down list, AM
    Peak Period Trips from the Matrix File drop-down list, Total (7-9)
    from the Matrix drop-down list, and type "10" in the Iterations edit
    box.

-   Step 4. In the Field column of the grid view, verify that \[Freeflow
    Time\] is chosen for Time and \[AB_AMCapacity/BA_AMCapacity\] is
    chosen for Capacity drop-down list. The other settings are correct.

-   Step 5. Click Options to display the Options dialog box. \\

-   Step 6. Check the Create Theme box, type "3" in the Max V/C edit box
    and click OK.

-   Step 7. Click OK to display the Output File Settings dialog box.

-   Step 8. Type "First Name-TA-UE" as the Flow Table file name in the
    Short File Name cell and click OK. TransCAD assigns the flow to the
    links in the network and displays the Results Summary dialog box.

-   Step 9. Click Close. TransCAD displays the results in a joined view
    and displays a color theme of the volume-to-capacity ratio and a
    scaled-symbol theme of flow on the map.

-   Step 10. Choose File > Close All and click No to close the map,
    dataview, and matrix without saving changes.

### Task 11: Performing Assignment with Critical Link Analysis

-   Step 1. Choose File > Open Workspace, then open the workspace
    TrafficAssignCriticalLink.wrk. TransCAD displays a map and a flow
    matrix. You want to assign flow to the links using the User
    Equilibrium model and report the O-D traffic over the Critical
    Links.

-   Step 2. Choose Planning > Static Traffic Assignment > Traffic
    Assignment to display the Traffic Assignment dialog box.

-   Step 3. Choose N-Conjugate UE from the Method drop-down list, AM
    Peak Period Trips from the Matrix File drop-down list, and Total
    (7-9) from the Matrix drop-down list.

-   Step 4. In the Field column of the grid, verify that \[Freeflow
    Time\] is chosen for Time row and \[AB_AMCapacity/BA_AMCapacity\] is
    chosen in the Capacity row.

-   Step 5. Type "10" in the Iterations edit box. The other settings are
    correct.

-   Step 6. Click Options to display the Options dialog box and click
    the Other Options tab.

-   Step 7. Check the Select Link/Zone Queries box to open the File Open
    dialog box. Choose the CriticalLink.qry query file and click Open.
    The queries appear in the scroll list.

-   Step 8. Highlight the I-495 Westbound query and click OK to return
    to the Traffic Assignment dialog box.

-   Step 9. Click OK to display the Output File Settings dialog box.

-   Step 10. Highlight and change the Flow Table file name to "First
    Name-TA-CF."

-   Step 11. Highlight and change the Critical Matrix file name to
    "First Name-TA-CM."

-   Step 12. Click OK. TransCAD assigns the flow to the links in the
    network and displays the Results Summary dialog box.

-   Step 13. Click Close. TransCAD displays the results in a joined view
    and displays the Critical Link Analysis matrix, indicating the O-D
    pairs and flows that utilize the critical link. The results are
    displayed in each direction of the link.

-   Step 14. Choose Map > Thematic Mapping > Size to display the Scaled
    Symbol Theme dialog box.

-   Step 15. Choose \[AB_Flow_I-495 Westbound\] near the button of the
    scroll list and click OK. TransCAD adds a scaled-symbol theme to the
    map showing flow patterns for everyone who travels over the critical
    links.

-   Step 16. Choose File > Close All and click No to close all of the
    windows without saving.

## Multi-Modal Multi-Class Assignment (MMA)

MMA is a flexible master assignment routine designed for use in major
metropolitan areas and is directly applicable in statewide or
interregional models. The MMA model is a generalized cost assignment
that lets you assign trips by individual modes or user classes to the
network simultaneously. This method allows you to explicitly model the
influence of toll facilities of all types, as well as HOV and HOT
facilities. Each mode or class can have different network exclusions,
congestion impacts (passenger car equivalent values), values of time,
and toll costs.

### Task 12: Performing Multi-Modal Assignment

-   Step 1. Choose File > Open Workspace, then open the workspace
    TrafficAssignMultiModal.wrk. TransCAD displays a map of highways in
    Massachusetts, along with a flow matrix for cars, light trucks and
    heavy trucks, and a toll matrix describing tolls between entry and
    exit nodes on the Massachusetts Turnpike. A network is also loaded.
    You want to assign the multiple-mode flow matrix to the network
    using fixed tolls and the toll matrix.

-   Step 2. Choose Highways from the drop-down list on the Standard
    toolbar.

-   Step 3. Choose Planning > Static Traffic Assignment > Multi-Modal
    Multi-Class Assignment to display the Multi-Modal Multi-Class
    Assignment dialog box.

-   Step 4. Verify that N Conjugate UE is chosen from the Method
    drop-down list, Bureau of Public Roads (BPR) is chosen from the
    Delay Function drop-down list and AM Trips (7:00-9:00) is chosen
    from the O-D Matrix drop-down list.

-   Step 5. Click Tolls to display the Toll Settings dialog box, choose
    Mass Pike Toll Schedule from the Toll Matrix drop-down list and
    click OK to return to return to the Multi-Modal Multi-Class
    Assignment box.

-   Step 6. Click on the Choose OD Classes button, highlight all
    available matrices and click on the Add >\> button to select all
    matrices and click OK.

-   Step 7. Make the following changes in the Cars -- Class 1 row: -
    Click on the cell in the Link Toll column and choose \[Car Toll\]
    from the drop-down list - Click on the cell in the OD Toll column
    and choose Cars -- Class 1 from the drop-down list

-   Step 8. Make the following changes in the Truck -- 4T row: - Click
    on the cell in the Link Toll column and choose \[Truck 4T Toll\]
    from the drop-down list - Click on the cell in the OD Toll column
    and choose Truck -- 4T from the drop-down list

-   Step 9. Make the following changes in the Trucks -- SU row: - Click
    on the cell in the PCE Global column and type "2.0" - Click on the
    cell in the Link Toll column and choose \[Truck SU Toll\] from the
    drop-down list - Click on the cell in the OD Toll column and choose
    Trucks -- SU from the drop-down list

-   Step 10. Make the following changes in the Trucks -- Combo row: -
    Click on the cell in the PCE Global column and type "3.0" - Click on
    the cell in the Link Toll column and choose \[Truck Combo Toll\]
    from the drop-down list - Click on the cell in the OD Toll column
    and choose Trucks -- Combo from the drop-down list - Click on the
    cell in the Exclusion Set column and choose Truck Combo Exclusion
    from the drop-down list

-   Step 11. In the Delay Function Parameters grid, verify that
    \[AB_FFTime/BA_FFTime\] is the field chosen for Time and
    \[AB_AMCapacity/BA_AMCapacity\] is the field chosen for Capacity.
    The other settings are correct.

-   Step 12. Click OK to display the Output File Settings dialog box.

-   Step 13. Type "First Name-TA-MMA" in the File Prefix edit box and
    click OK. TransCAD assigns the flows to the links in the network and
    displays the Results Summary dialog box.

-   Step 14. Click Close. TransCAD displays the results in a joined
    view.

-   Step 15. Choose Map > Thematic Mapping > Size to display the Scaled
    Symbol Theme dialog box.

-   Step 16. Choose AB_Flow_Truck -- Combo from the scroll list and
    click OK. TransCAD adds a scaled-symbol theme of the assigned flows
    on the map.

-   Step 17. Choose File > Close All and click No to All to close all of
    the windows without saving.

# Part II: Network and Route Analysis

Vehicle Routing Many businesses and government agencies transport goods
from one or more central locations to a set of destinations. It is
important to manage these operations efficiently, both to reduce
operating costs and to ensure that pickups and deliveries adhere to
reasonable service standards. This general problem is known as the
vehicle routing problem. Solving the vehicle routing problem involves
determining how many vehicles are required to service the destinations
and developing a route and schedule for each one. Because there are many
variations of the problem, it can be very difficult to solve. TransCAD
provides a rich set of vehicle routing tools that solve various types of
routing problems.

### Task 13: Solving a Vehicle Routing Problem

-   Step 1. Choose File > Open, then open the map
    VehicleRoutingwithTimeWindows.map. TransCAD displays a map with two
    depots and 25 stops.

-   Step 2. Choose File > Open and open the network BOSTON.NET.

-   Step 3. Choose Routing/Logistics > Vehicle Routing to display the
    Vehicle Routing Wizard.

-   Step 4. Click the Create New Vehicle Routes radio button, verify
    that Delivery is chosen from the Operations Mode drop-down list and
    click Next to display the Customers page.

-   Step 5. Notice that TransCAD already has chosen to use all features
    in the Clients layer and has found the fields for name, demand,
    service time, and time window. Click Next to display the Depots
    page.

-   Step 6. Notice that TransCAD already has chosen to use all features
    in the Depots layer and has found the fields for name, open time,
    and close time. Click Next to display the Vehicles page.

-   Step 7. Click "green plus sign" six times to add 6 vehicles.

-   Step 8. Click and drag to highlight all of the cells in the Cost
    column and type 100 to set the costs for all six vehicles.

-   Step 9. Click and drag to highlight all of the cells in the Capacity
    column and type 50 to set the capacities for all six vehicles.

-   Step 10. For vehicles 4-6, choose Free Port Depot from the drop-down
    list in the Depot column.

-   Step 11. Click Next to display the Options page.

-   Step 12. Enter 8 in the Maximum Route Duration box, choose Time (in
    hours) from the Balance Routes by drop-down list, and click Finish.
    TransCAD displays the Save Vehicle Routing Results In dialog box.

-   Step 13. Right-click in the dialog box, choose New > Folder, name
    the folder "First Name-VRP-Results," and click Select Folder.

-   Step 14. Click OK in the status dialog box. TransCAD adds the routes
    to the map and opens the Vehicle Routing Manager. Notice the five
    routes have approximately even durations.

-   Step 15. Click "plus sign" next to a route to see the stops that
    route services.

-   Step 16. Right-click the itinerary description at the top of the
    list and choose Create Report. TransCAD creates a PDF report. Scroll
    through the PDF to see the itinerary for each route. Close the
    report when you are done.

## Network Flow Models

TransCAD includes a set of procedures for solving network flow problems.
These problems involve efficient delivery of goods or services and arise
both in transportation and in many other contexts. For example: - You
need to ship an inventory of goods from 15 warehouses to 100 retail
centers, each with a given demand, and you want to determine which
warehouses should service which retail centers to minimize the total
transportation cost. - You need to route empty rail cars from their
current locations to locations where they are required for new loads,
taking into account rail traffic density by link.

### Task 14: Solving a Transportation Problem and Displaying Output Flow

-   Step 1. Choose File > Open Workspace, then open the workspace
    TransportationProblem.wrk. TransCAD displays a map of Washington
    State. On the map, there are three warehouses and 20 customers. You
    want to determine which warehouse ships tSo which customer. Also
    opened is a travel time matrix between each warehouse and each
    customer.

-   Step 2. Choose Routing/Logistics > The Transportation Problem to
    display The Transportation Problem dialog box.

-   Step 3. Choose WAREHOUSE from the Layer drop-down list under Origin
    Settings and choose CUSTOMER from the Layer drop-down list under
    Destination Settings. Step 4. Verify that Wa_hwy.net is the active
    network.

-   Step 5. Choose TIME from the Cost Field drop-down list.

-   Step 6. The other settings are correct. Click OK to display the
    Output File Settings dialog box.

-   Step 7. Change the output file names as done above and click OK.
    TransCAD solves the Transportation Problem and assigns the shipments
    to links in the network. A joined view is opened showing the flow on
    each link.

-   Step 8. Click on the map window or choose Window > U.S. Highways to
    make the map the active window. TransCAD shows a scaled-symbol theme
    showing the flow on each link.\
    Step 9. Choose File > Close All and click No to close the map and
    matrix without saving any changes.

## Facility Location Models

Facility Location Models are used to identify good locations for
warehouses, hospitals, retail stores, manufacturing facilities, and
other types of facilities. In general, the goal in locating such
facilities is either to provide a high level of service, to minimize
operating costs, or to maximize profits. TransCAD solves many different
types of facility location problems, with applications in both the
public and private sectors. Here are two examples: - You need to
determine the best location for a new branch of a public library. Your
goal is to provide the best overall level of access to city residents. -
You need to determine the best location for a new police station. Your
goal is to reduce the maximum distance a patrol car needs to travel from
the station to a resident's home.

### Task 15: Solving a Facility Location Problem

-   Step 1. Choose File > Open Workspace, then open the workspace
    FacilityLocation.wrk. TransCAD displays a map of the Northeast Sales
    Region. On the map, there are 46 customers, one existing facility
    and 8 candidate facilities. A matrix file is also opened. You want
    to determine what two facilities to add to minimize shipping cost.\
    Step 2. Choose Routing/Logistics > Facility Location to display the
    Facility Location dialog box.

-   Step 3. Type "2" in the \# New Facilities edit box. Step 4. Choose
    Facility from the Layer drop-down list under Facility Settings.

-   Step 5. Choose Customer from the Layer drop-down list under Client
    Settings.

-   Step 6. Choose Demand from the Weight drop-down list.

-   Step 7. Click OK to display the Output File Settings dialog box.

-   Step 8. Type "First Name-FL" in the Short File Name cell and click
    OK. TransCAD determines the two new facilities to open that, in
    conjunction with the existing facility in New York, will minimize
    the cost of shipping to the 46 customers. A selection set named New
    Facilities, containing these facilities, is displayed on the map. A
    table is joined to the Customer layer showing which facility will
    service each customer. The results summary is also displayed. Click
    Close to close the Results Summary dialog box.

-   Step 9. Click on the map or choose Window > Map1 to make the map the
    active window and see the new facilities to open. Step 10. Choose
    File > Close All and click No to close the map, matrix and joined
    view without saving nay changes.
